### ISSUE TITLE
GetAdapter method not found

### ISSUE THREAD

**Issue by ParticularName** [mallibone/PclSample#1]
GetAdapter method not found in people. 

PeopleListView.Adapter = Vm.People.GetAdapter(GetPersonView);

**Comment by mallibone** [comment]
@saravananmaruthanayakam have you restored the NuGet packages and performed a build? The error should then disappear.

**Comment by ParticularName** [comment]
@mallibone Thanks a lot.It's working now.

**Comment by ParticularName** [comment]
I am facing another problem.Getting exception at this line in
ViewModelLocator.

     public MainViewModel MainViewModel =>
SimpleIoc.Default.GetInstance<MainViewModel>();

System Invalid Cast Exception&System.Reflection.TargetInvocationException.
can you help me?

**Comment by mallibone** [comment]
On what platform did you build i.e. with which build config?

**Comment by ParticularName** [comment]
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

**Comment by mallibone** [comment]
Sorry I meant for which target platform e.g. : iOS Release Build, also have a look what for s configured in the csproj file for the build. I'm guessing something is being kicked out during the compilation and that is why you are seeing this behaviour.

**Comment by ParticularName** [comment]
Android Build

**Comment by mallibone** [comment]
Okay I think I found the issue.. If you pull the source it should be working now. Had to bump the SDK it was compiled against.

**Comment by ParticularName** [comment]
Sorry for the delay.It's working .I have cleaned and done the rebuild .It
works fine!Thanks

**Comment by ParticularName** [comment]
If you don't mind by any chance do you have any idea about the Cross
platform PCL component that does the data encryption using available
libraries tweaking or shared projects rather than dependency injection  ?
